poliastro_atmo_drag:
  ros__parameters:
    earth_r: 6378.1366
    a: 6550.85876692
    ecc: 0.0
    inc: 0.0
    raan: 0.0
    argp: 0.0
    nu: 0.0
    c_d: 2.2
    t_limit: 1.0
    publish_freq: 10.0
    